language: c++

cache: ccache

git:
  depth: 1

dist: xenial

sudo: true

install:
 - sudo apt-get install --allow-unauthenticated libboost-thread-dev libboost-iostreams-dev libboost-date-time-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-chrono-dev libboost-test-dev libboost-context-dev libboost-regex-dev libboost-coroutine-dev cmake parallel

addons:
  sonarcloud:
    organization: "soundac"
    token:
      secure: "Cr3q74yHUsS+kcAsAtB+yB2AyDptL8Rpmw+Q8HR+1MIEnIqyp5BLGNzOZnlucNQwUSUeVF81MpVTRgJT7zzVRa3XbVIngT25a3mm7zgULtG+RJG2rIFoeFWmgmj8kf+1HAis2lsJNUDylhrdumRQS3fMXBA/5Hz4Sbrve/TUg40RutAOsaXipwxqsanxnt/vwFndbb8Y/wprmgHrj45IMG+5bdJ6+DjaahJ9c1QDtWhtn9kPVYCJlO+XRzbHoVCOJOw8+r3FW8I5bDKMxbwGnAcAt4h0ZaxWtUSvt/iECpZqmOgirmVKQ9FJFzcCWBw+PY5Z+bnjwLjDCm2HqoNDk08cWLTn4Na/ZFO5AbBjS9L2VYC5PLpboTJnAygKcEcFDxsNDpnJK5mbcyV/Yzcmwwu5bIEfaDJS4aE1hVCqKhWP7Ecg2QxLtDSG4NHmyrG0CCUorhSemgUK5XvZ9QsSMqnBYl5ee9y/mc6swjHTK3DshJOHzWHO0QpoHg+fv5At7CXWvF/0F7/l24RvCweSni6/eT40MsM6tQCAEJRe6RFBeZAXs1RW+uh+A/CVeTKjNOtJNsV8AmJyu3bR3C7Kug3t+jbZ7cqms+wxyeIt01nYkgJM84kAnnJI51x+c3YtdJ4zK7dic7XWfy0jWdGVb9/JydPmhxI2PEKpPqnFmyk="

env:
  global:
    - CCACHE_COMPRESS=exists_means_true
    - CCACHE_MAXSIZE=1Gi
    - CCACHE_SLOPPINESS=include_file_ctime,include_file_mtime,time_macros

script:
 - ccache -s
 - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage -DBoost_USE_STATIC_LIBS=OFF  -DCMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON .
 - 'which build-wrapper-linux-x86-64 && build-wrapper-linux-x86-64 --out-dir bw-output make -j 2 || make -j 2'
 - set -o pipefail
 - tests/all_tests 2>&1 | cat
 - tests/api 2>&1 | cat
 - tests/ecc_test README.md 2>&1 | cat
 - tests/log_test 2>&1 | cat
 - tests/sha_test 2>&1 | cat
 - 'find CMakeFiles/fc.dir -type d | while read d; do gcov -o "$d" "${d/CMakeFiles*.dir/./}"/*.cpp; done >/dev/null'
 - 'which sonar-scanner && sonar-scanner || true'
 - ccache -s
